apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/nats.yaml
- manifests/dispatcher.yaml
- manifests/worker.yaml
- manifests/autoscaler.yaml
images:
- name: WORKER_IMAGE
  newName: docker.io/pkbs/pkbs-worker
  newTag: latest
