apiVersion: v1
kind: Pod
metadata:
  name: dispatcher
spec:
      containers:
        - name: dispatcher
          image: WORKER_IMAGE
          imagePullPolicy: Always
          command: ["/bin/sleep"]
          args: ["365d"]
