apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud-ss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud
        ports:
        - name: web
          containerPort: 80
        env:
        - name: SQLITE_DATABASE
          value: mynextclouddb
        - name: NEXTCLOUD_ADMIN_USER
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: WEBDAV_USER
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: WEBDAV_PASSWD
        # nextcloud-svc is required for pods
        # 10.* is required to access the service from local network
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: NEXTCLOUD_TRUSTED_DOMAINS
        volumeMounts:
        - name: nextcloud-storage
          mountPath: /var/www/html
        imagePullPolicy: IfNotPresent
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                - "true"
            weight: 1
  volumeClaimTemplates:
  - metadata:
      name: nextcloud-storage
    spec:
      resources:
        requests:
          storage: 100Mi
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
  serviceName: nextcloud
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-svc
  labels:
    app: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
  - name: web
    port: 80
  clusterIP: None
