apiVersion: v1
kind: Pod
metadata:
  name: rsyslog
  labels:
    app: rsyslog
spec:
  containers:
    - name: rsyslog
      image: rsyslog/syslog_appliance_alpine
      envFrom:
        - configMapRef:
            name: rsyslog-config
      imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: rsyslog-svc
  labels:
    app: rsyslog
spec:
  selector:
    app: rsyslog
  ports:
    - name: rsyslog
      protocol: UDP
      port: 514
      targetPort: 514
  clusterIP: None
