apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: WORKER_IMAGE
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WEBDAV_URL
          value: http://nextcloud-svc/remote.php/dav/files
        # FIXME secrets
        - name: WEBDAV_USER
          value: admin
        - name: WEBDAV_PASSWD
          value: admin
        - name: WEBDAV_PATH
          value: pkebs
        - name: WEBDAV_UPLOAD
          value: zip

