apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: WORKER_IMAGE
        command: ["./worker.py", "--syslog"]
        envFrom:
        - configMapRef:
            name: env-config
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: "900m"
          requests:
            cpu: "300m"
        imagePullPolicy: Always
